openapi: 3.0.2
info:
  title: Simple Api
  description: Test
  version: 0.1.9

servers:
  - url : http://localhost:8080/v1

tags:
  - name: users

paths:
  /users:
    get:
      tags:
        - users
      summary: Return a list of users
      description: Test
      responses:
        '200' :
          description: A json array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      tags:
        - users
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      summary: Post an user
      description: Create
      responses:
        '201':
          content:
            application/json:
              schema:
                type: string
                value: "success"


components:
  schemas:

    UserRequest:
      type: object
      properties:
        name:
          type: string
        addresses:
          type: array
          items:
            type: string